# Generated by Django 3.2.13 on 2022-04-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sumnumbers',
            name='id_task',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
